-- =============================================================================
-- INNOVER CRM - ESQUEMA COMPLETO DE BASE DE DATOS Y AUTENTICACIÓN SUPABASE
-- Compatible con Supabase PostgreSQL, Supabase Auth y Supabase Storage
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. EXTENSIONES
-- -----------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- -----------------------------------------------------------------------------
-- 2. TABLA: ORGANIZACIONES (Multi-Tenant)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.organizations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  legal_name text,
  tax_id text,
  email text,
  phone text,
  address text,
  logo_url text,
  timezone text NOT NULL DEFAULT 'America/Caracas',
  currency text NOT NULL DEFAULT 'USD',
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'inactive')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 3. TABLA: AGENTES / ASESORES (Vinculada a auth.users de Supabase)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.agents (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL UNIQUE,
  organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  password text, -- Hash de respaldo para compatibilidad
  role text NOT NULL DEFAULT 'agent' CHECK (role IN ('admin', 'agent')),
  department text NOT NULL DEFAULT 'soporte' CHECK (department IN ('cobranza', 'soporte', 'general')),
  status text NOT NULL DEFAULT 'offline' CHECK (status IN ('online', 'busy', 'offline', 'inactive')),
  initials text,
  avatar_color text DEFAULT '#4f8ef7',
  avatar_bg text DEFAULT 'rgba(79,142,247,.15)',
  max_conversations integer DEFAULT 10,
  ui_accent text,
  ui_mode text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS agents_user_id_idx ON public.agents (user_id);
CREATE INDEX IF NOT EXISTS agents_org_idx ON public.agents (organization_id);

-- Migración segura si la tabla public.agents ya existía previamente:
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
      AND table_name = 'agents' 
      AND column_name = 'department'
  ) THEN
    ALTER TABLE public.agents 
    ADD COLUMN department text NOT NULL DEFAULT 'soporte' 
    CHECK (department IN ('cobranza', 'soporte', 'general'));
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS agents_dept_idx ON public.agents (department);

-- -----------------------------------------------------------------------------
-- 4. TABLA: MIEMBROS DE ORGANIZACIÓN
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.organization_members (
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  agent_id integer NOT NULL REFERENCES public.agents(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'advisor' CHECK (role IN ('owner', 'admin', 'supervisor', 'advisor')),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'invited', 'inactive')),
  joined_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (organization_id, agent_id)
);

-- -----------------------------------------------------------------------------
-- 5. TABLA: CLIENTES
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text NOT NULL,
  phone text NOT NULL,
  plan text,
  zone text,
  account text DEFAULT 'Prospecto',
  wispro_id text,
  whatsapp_id text,
  wa_name text,
  color text,
  bg text,
  initials text,
  envoicing text,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS clients_phone_idx ON public.clients (phone);
CREATE INDEX IF NOT EXISTS clients_org_idx ON public.clients (organization_id);
CREATE INDEX IF NOT EXISTS clients_wispro_id_idx ON public.clients (wispro_id);

-- -----------------------------------------------------------------------------
-- 6. TABLA: CONVERSACIONES
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.conversations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,
  client_id bigint REFERENCES public.clients(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'abierto' CHECK (status IN ('abierto', 'proceso', 'resuelto')),
  human_mode boolean NOT NULL DEFAULT false,
  bot_engine text DEFAULT 'ai',
  label_ids integer[] DEFAULT '{}'::integer[],
  preview text,
  unread integer DEFAULT 0,
  agent_id integer REFERENCES public.agents(id) ON DELETE SET NULL,
  agent_control text,
  customer_phone text,
  wa_phone_number_id text,
  last_message_at timestamptz,
  updated_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS conversations_org_status_idx ON public.conversations (organization_id, status);
CREATE INDEX IF NOT EXISTS conversations_client_idx ON public.conversations (client_id);
CREATE INDEX IF NOT EXISTS conversations_agent_idx ON public.conversations (agent_id);
CREATE INDEX IF NOT EXISTS conversations_updated_idx ON public.conversations (updated_at DESC);

-- -----------------------------------------------------------------------------
-- 7. TABLA: MENSAJES
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,
  conversation_id bigint NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
  wa_message_id text,
  type text NOT NULL CHECK (type IN ('in', 'out', 'note')),
  content text NOT NULL DEFAULT '',
  media_url text,
  media_type text CHECK (media_type IN ('audio', 'image', 'video', 'document', 'location')),
  mime_type text,
  caption text,
  metadata jsonb DEFAULT '{}'::jsonb,
  latitude numeric,
  longitude numeric,
  location_name text,
  location_address text,
  sender_type text NOT NULL CHECK (sender_type IN ('client', 'agent', 'bot')),
  sent_by text,
  status text CHECK (status IN ('sent', 'delivered', 'read', 'failed')),
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS messages_conv_idx ON public.messages (conversation_id, created_at);
CREATE INDEX IF NOT EXISTS messages_wa_idx ON public.messages (wa_message_id);
CREATE INDEX IF NOT EXISTS messages_org_idx ON public.messages (organization_id);

-- -----------------------------------------------------------------------------
-- 8. TABLA: TICKETS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tickets (
  id text PRIMARY KEY,
  organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,
  client_id bigint REFERENCES public.clients(id) ON DELETE CASCADE,
  type text NOT NULL,
  status text NOT NULL DEFAULT 'Abierto' CHECK (status IN ('Abierto', 'En proceso', 'Resuelto')),
  agent text NOT NULL,
  description text,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS tickets_org_idx ON public.tickets (organization_id);
CREATE INDEX IF NOT EXISTS tickets_client_idx ON public.tickets (client_id);

-- -----------------------------------------------------------------------------
-- 9. TABLA: ETIQUETAS (Labels)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.labels (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text NOT NULL,
  color text NOT NULL,
  bg text NOT NULL,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS labels_org_idx ON public.labels (organization_id);

-- -----------------------------------------------------------------------------
-- 10. TABLA: RESPUESTAS RÁPIDAS (Quick Replies)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.quick_replies (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,
  title text NOT NULL,
  shortcut text,
  content text NOT NULL,
  category text,
  is_active boolean DEFAULT true,
  created_by integer REFERENCES public.agents(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS quick_replies_org_idx ON public.quick_replies (organization_id);

-- -----------------------------------------------------------------------------
-- 11. TABLAS: AJUSTES CRM E HISTORIAL
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.crm_settings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE UNIQUE,
  bot_engine text DEFAULT 'ai',
  ai_model text DEFAULT 'llama-3.3-70b-versatile',
  ai_system_prompt text,
  payment_success_message text,
  ai_recovery_messages jsonb,
  office_hours jsonb,
  after_hours_payments jsonb,
  ui_accent text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  updated_by integer REFERENCES public.agents(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.crm_settings_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,
  changed_by integer REFERENCES public.agents(id) ON DELETE SET NULL,
  ai_model text,
  ai_system_prompt text,
  created_at timestamptz DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 12. TABLAS: HISTORIAL DE CONVERSACIONES ARCHIVADAS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.conversation_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,
  client_id bigint REFERENCES public.clients(id) ON DELETE SET NULL,
  agent_id integer REFERENCES public.agents(id) ON DELETE SET NULL,
  client_name text,
  client_phone text,
  client_plan text,
  client_zone text,
  client_account text,
  resolved_at timestamptz NOT NULL DEFAULT now(),
  resolved_by integer REFERENCES public.agents(id) ON DELETE SET NULL,
  human_mode boolean DEFAULT false,
  label_ids integer[] DEFAULT '{}'::integer[],
  wa_phone_number_id text,
  total_messages integer DEFAULT 0,
  first_message_at timestamptz,
  last_message_at timestamptz,
  summary text,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS conv_hist_org_idx ON public.conversation_history (organization_id);
CREATE INDEX IF NOT EXISTS conv_hist_client_idx ON public.conversation_history (client_id);
CREATE INDEX IF NOT EXISTS conv_hist_resolved_idx ON public.conversation_history (resolved_at DESC);

CREATE TABLE IF NOT EXISTS public.history_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,
  history_id bigint NOT NULL REFERENCES public.conversation_history(id) ON DELETE CASCADE,
  source_message_id bigint,
  source_conversation_id bigint,
  type text NOT NULL,
  content text NOT NULL DEFAULT '',
  sender_type text NOT NULL,
  sent_by text,
  media_url text,
  media_type text,
  mime_type text,
  caption text,
  metadata jsonb DEFAULT '{}'::jsonb,
  latitude numeric,
  longitude numeric,
  location_name text,
  location_address text,
  wa_message_id text,
  status text,
  created_at timestamptz DEFAULT now(),
  archived_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS hist_messages_history_idx ON public.history_messages (history_id);
CREATE INDEX IF NOT EXISTS hist_messages_org_idx ON public.history_messages (organization_id);

-- -----------------------------------------------------------------------------
-- 13. TABLA: PAGOS REGISTRADOS (CRM Payments)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.crm_payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  client_id bigint REFERENCES public.clients(id) ON DELETE SET NULL,
  conversation_id bigint REFERENCES public.conversations(id) ON DELETE SET NULL,
  message_id bigint UNIQUE,
  submitted_by_agent_id integer REFERENCES public.agents(id) ON DELETE SET NULL,
  wispro_client_id text,
  client_name text,
  cedula text,
  phone_id text,
  amount numeric(12,2),
  amount_raw text,
  bank text,
  transaction_code text,
  payment_date date DEFAULT CURRENT_DATE,
  comment text,
  status text NOT NULL DEFAULT 'RECIBIDO' CHECK (status IN ('RECIBIDO', 'EN_PROCESO', 'APROBADO', 'RECHAZADO', 'DUPLICADO', 'ERROR')),
  source text NOT NULL DEFAULT 'ai' CHECK (source IN ('ai', 'advisor', 'manual', 'import', 'external_api')),
  external_payment_id text,
  external_api_status integer,
  external_response jsonb,
  error_message text,
  receipt_media_url text,
  receipt_metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS crm_payments_org_status_idx ON public.crm_payments (organization_id, status);
CREATE INDEX IF NOT EXISTS crm_payments_date_idx ON public.crm_payments (payment_date DESC);
CREATE INDEX IF NOT EXISTS crm_payments_msg_idx ON public.crm_payments (message_id);

-- -----------------------------------------------------------------------------
-- 14. TABLAS: TRAZABILIDAD Y AUDITORÍA DE IA
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ai_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  conversation_id bigint NOT NULL,
  trigger_message_id bigint,
  status text NOT NULL DEFAULT 'started',
  intent text,
  model text,
  circuit_open boolean DEFAULT false,
  started_at timestamptz DEFAULT now(),
  completed_at timestamptz,
  duration_ms integer,
  metadata jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public.ai_tool_invocations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  conversation_id bigint NOT NULL,
  run_id text,
  tool_name text NOT NULL,
  args jsonb DEFAULT '{}'::jsonb,
  result jsonb DEFAULT '{}'::jsonb,
  ok boolean NOT NULL DEFAULT true,
  duration_ms integer,
  error text,
  created_at timestamptz DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 15. TABLAS: ASIGNACIONES Y EVENTOS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.conversation_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  conversation_id bigint NOT NULL,
  agent_id integer REFERENCES public.agents(id) ON DELETE SET NULL,
  assigned_by integer REFERENCES public.agents(id) ON DELETE SET NULL,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  unassigned_at timestamptz,
  reason text
);
CREATE INDEX IF NOT EXISTS conv_assign_metrics_idx ON public.conversation_assignments (organization_id, agent_id, assigned_at DESC);

CREATE TABLE IF NOT EXISTS public.conversation_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  conversation_id bigint NOT NULL,
  agent_id integer REFERENCES public.agents(id) ON DELETE SET NULL,
  event_type text NOT NULL CHECK (
    event_type IN ('created', 'assigned', 'first_response', 'resolved', 'reopened', 'transferred')
  ),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS conv_events_metrics_idx ON public.conversation_events (organization_id, event_type, occurred_at DESC);

-- -----------------------------------------------------------------------------
-- 16. TABLA: INTEGRACIONES POR ORGANIZACIÓN (Wispro, WhatsApp)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.organization_integrations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  provider text NOT NULL CHECK (provider IN ('wispro', 'whatsapp')),
  status text NOT NULL DEFAULT 'disconnected' CHECK (status IN ('disconnected', 'pending', 'connected', 'error')),
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  credentials_encrypted text,
  last_verified_at timestamptz,
  last_error text,
  configured_by integer REFERENCES public.agents(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization_id, provider)
);

-- -----------------------------------------------------------------------------
-- 17. TRIGGERS DE MÉTRICAS Y TIEMPO DE RESPUESTA
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.capture_conversation_metrics()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.conversation_events (
      organization_id, conversation_id, agent_id, event_type, occurred_at
    ) VALUES (
      NEW.organization_id, NEW.id, NEW.agent_id, 'created', coalesce(NEW.created_at, now())
    );
    RETURN NEW;
  END IF;

  IF NEW.agent_id IS DISTINCT FROM OLD.agent_id AND NEW.agent_id IS NOT NULL THEN
    UPDATE public.conversation_assignments
    SET unassigned_at = now()
    WHERE organization_id = NEW.organization_id AND conversation_id = NEW.id AND unassigned_at IS NULL;

    INSERT INTO public.conversation_assignments (
      organization_id, conversation_id, agent_id, assigned_at
    ) VALUES (NEW.organization_id, NEW.id, NEW.agent_id, now());

    INSERT INTO public.conversation_events (
      organization_id, conversation_id, agent_id, event_type
    ) VALUES (
      NEW.organization_id, NEW.id, NEW.agent_id,
      CASE WHEN OLD.agent_id IS NULL THEN 'assigned' ELSE 'transferred' END
    );
  END IF;

  IF NEW.status = 'resuelto' AND OLD.status IS DISTINCT FROM 'resuelto' THEN
    INSERT INTO public.conversation_events (
      organization_id, conversation_id, agent_id, event_type
    ) VALUES (NEW.organization_id, NEW.id, NEW.agent_id, 'resolved');
  ELSIF OLD.status = 'resuelto' AND NEW.status IS DISTINCT FROM 'resuelto' THEN
    INSERT INTO public.conversation_events (
      organization_id, conversation_id, agent_id, event_type
    ) VALUES (NEW.organization_id, NEW.id, NEW.agent_id, 'reopened');
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS conversations_metrics_trigger ON public.conversations;
CREATE TRIGGER conversations_metrics_trigger
AFTER INSERT OR UPDATE OF agent_id, status ON public.conversations
FOR EACH ROW EXECUTE FUNCTION public.capture_conversation_metrics();

CREATE OR REPLACE FUNCTION public.capture_first_agent_response()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  conv_created_at timestamptz;
  conv_agent_id integer;
BEGIN
  IF NEW.type <> 'out' OR NEW.sender_type <> 'agent' THEN
    RETURN NEW;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.conversation_events
    WHERE organization_id = NEW.organization_id
      AND conversation_id = NEW.conversation_id
      AND event_type = 'first_response'
  ) THEN
    RETURN NEW;
  END IF;

  SELECT created_at, agent_id INTO conv_created_at, conv_agent_id
  FROM public.conversations
  WHERE id = NEW.conversation_id AND organization_id = NEW.organization_id;

  INSERT INTO public.conversation_events (
    organization_id, conversation_id, agent_id, event_type, metadata, occurred_at
  ) VALUES (
    NEW.organization_id, NEW.conversation_id, conv_agent_id, 'first_response',
    jsonb_build_object('duration_ms', greatest(0, floor(extract(epoch FROM (coalesce(NEW.created_at, now()) - conv_created_at)) * 1000))),
    coalesce(NEW.created_at, now())
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS messages_first_response_trigger ON public.messages;
CREATE TRIGGER messages_first_response_trigger
AFTER INSERT ON public.messages
FOR EACH ROW EXECUTE FUNCTION public.capture_first_agent_response();

-- -----------------------------------------------------------------------------
-- 18. INTEGRACIÓN BIDIRECCIONAL CON SUPABASE AUTH (auth.users)
-- Sincroniza automáticamente usuarios de Supabase Auth con public.agents
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  target_org_id uuid;
  user_name text;
  user_role text;
  user_dept text;
  member_role text;
  new_agent_id integer;
BEGIN
  -- 1. Verificar si viene organization_id en los metadatos del usuario
  IF new.raw_user_meta_data->>'organization_id' IS NOT NULL THEN
    BEGIN
      target_org_id := (new.raw_user_meta_data->>'organization_id')::uuid;
    EXCEPTION WHEN OTHERS THEN
      target_org_id := NULL;
    END;
  END IF;

  -- Si no viene, obtener la organización por defecto
  IF target_org_id IS NULL THEN
    SELECT id INTO target_org_id FROM public.organizations WHERE slug = 'innover' LIMIT 1;
    IF target_org_id IS NULL THEN
      SELECT id INTO target_org_id FROM public.organizations ORDER BY created_at ASC LIMIT 1;
    END IF;
  END IF;

  user_name := coalesce(
    new.raw_user_meta_data->>'name',
    new.raw_user_meta_data->>'full_name',
    split_part(new.email, '@', 1)
  );

  user_role := coalesce(new.raw_user_meta_data->>'role', 'agent');
  IF user_role NOT IN ('admin', 'agent') THEN
    user_role := 'agent';
  END IF;

  user_dept := coalesce(new.raw_user_meta_data->>'department', 'soporte');
  IF user_dept NOT IN ('cobranza', 'soporte', 'general') THEN
    user_dept := 'soporte';
  END IF;

  member_role := coalesce(
    new.raw_user_meta_data->>'org_role',
    CASE WHEN user_role = 'admin' THEN 'admin' ELSE 'advisor' END
  );
  IF member_role NOT IN ('owner', 'admin', 'supervisor', 'advisor') THEN
    member_role := 'advisor';
  END IF;

  -- Insertar o actualizar agente en public.agents
  INSERT INTO public.agents (
    user_id,
    organization_id,
    name,
    email,
    role,
    department,
    status,
    initials
  ) VALUES (
    new.id,
    target_org_id,
    user_name,
    new.email,
    user_role,
    user_dept,
    'offline',
    upper(substring(user_name from 1 for 2))
  )
  ON CONFLICT (email) DO UPDATE
    SET user_id = new.id,
        organization_id = coalesce(public.agents.organization_id, target_org_id),
        updated_at = now()
  RETURNING id INTO new_agent_id;

  -- Vincular a miembros de la organización
  IF target_org_id IS NOT NULL AND new_agent_id IS NOT NULL THEN
    INSERT INTO public.organization_members (organization_id, agent_id, role, status)
    VALUES (
      target_org_id,
      new_agent_id,
      member_role,
      'active'
    )
    ON CONFLICT (organization_id, agent_id) DO NOTHING;
  END IF;

  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();

CREATE OR REPLACE FUNCTION public.handle_update_auth_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.agents
  SET email = new.email,
      updated_at = now()
  WHERE user_id = new.id;
  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_updated ON auth.users;
CREATE TRIGGER on_auth_user_updated
AFTER UPDATE OF email ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_update_auth_user();

-- -----------------------------------------------------------------------------
-- 19. HABILITAR ROW LEVEL SECURITY (RLS) Y POLÍTICAS DE ACCESO
-- -----------------------------------------------------------------------------
DO $$
DECLARE
  t text;
  all_tables text[] := ARRAY[
    'organizations', 'organization_members', 'organization_integrations',
    'agents', 'clients', 'conversations', 'messages', 'tickets', 'labels',
    'quick_replies', 'crm_settings', 'crm_settings_history', 'conversation_history',
    'history_messages', 'crm_payments', 'ai_runs', 'ai_tool_invocations',
    'conversation_assignments', 'conversation_events'
  ];
BEGIN
  FOREACH t IN ARRAY all_tables LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS service_role_all ON public.%I', t);
    EXECUTE format('CREATE POLICY service_role_all ON public.%I FOR ALL TO service_role USING (true) WITH CHECK (true)', t);
    EXECUTE format('DROP POLICY IF EXISTS auth_users_all ON public.%I', t);
    EXECUTE format('CREATE POLICY auth_users_all ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', t);
  END LOOP;
END $$;

-- Permitir suscripciones Supabase Realtime para clientes con anon key
DROP POLICY IF EXISTS anon_read_messages ON public.messages;
CREATE POLICY anon_read_messages ON public.messages FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS anon_read_conversations ON public.conversations;
CREATE POLICY anon_read_conversations ON public.conversations FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS anon_read_clients ON public.clients;
CREATE POLICY anon_read_clients ON public.clients FOR SELECT TO anon USING (true);

-- -----------------------------------------------------------------------------
-- 20. HABILITAR SUPABASE REALTIME
-- -----------------------------------------------------------------------------
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.messages, public.conversations, public.clients;
  EXCEPTION
    WHEN duplicate_object THEN NULL;
  END;
END $$;

-- -----------------------------------------------------------------------------
-- 21. BUCKETS DE STORAGE (WhatsApp / CRM Multimedia)
-- -----------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES 
  ('audio-bucket', 'audio-bucket', true),
  ('image-bucket', 'image-bucket', true),
  ('video-bucket', 'video-bucket', true),
  ('document-bucket', 'document-bucket', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Políticas de Storage
DROP POLICY IF EXISTS "Public Access Audio" ON storage.objects;
CREATE POLICY "Public Access Audio" ON storage.objects FOR SELECT USING (bucket_id IN ('audio-bucket', 'image-bucket', 'video-bucket', 'document-bucket'));

DROP POLICY IF EXISTS "Service and Auth Upload" ON storage.objects;
CREATE POLICY "Service and Auth Upload" ON storage.objects FOR ALL USING (bucket_id IN ('audio-bucket', 'image-bucket', 'video-bucket', 'document-bucket')) WITH CHECK (bucket_id IN ('audio-bucket', 'image-bucket', 'video-bucket', 'document-bucket'));

-- -----------------------------------------------------------------------------
-- 22. DATOS SEMILLA: ORGANIZACIÓN INICIAL Y AJUSTES
-- -----------------------------------------------------------------------------
INSERT INTO public.organizations (id, name, slug)
VALUES ('00000000-0000-4000-8000-000000000001', 'Innover', 'innover')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.crm_settings (organization_id, bot_engine, ai_model)
VALUES ('00000000-0000-4000-8000-000000000001', 'ai', 'llama-3.3-70b-versatile')
ON CONFLICT (organization_id) DO NOTHING;

-- Etiquetas operativas
INSERT INTO public.labels (organization_id, name, color, bg)
VALUES
  ('00000000-0000-4000-8000-000000000001', 'verificar pago', '#f59e0b', 'rgba(245, 158, 11, 0.15)'),
  ('00000000-0000-4000-8000-000000000001', 'pagado api', '#10b981', 'rgba(16, 185, 129, 0.15)'),
  ('00000000-0000-4000-8000-000000000001', 'soporte', '#3b82f6', 'rgba(59, 130, 246, 0.15)'),
  ('00000000-0000-4000-8000-000000000001', 'ia error', '#ef4444', 'rgba(239, 68, 68, 0.15)')
ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- 23. DATOS SEMILLA: USUARIO ADMINISTRADOR EN SUPABASE AUTH Y AGENTS
-- Email: admin@innover.com
-- Contraseña por defecto: Admin123!
-- -----------------------------------------------------------------------------
DO $$
DECLARE
  default_user_id uuid := 'a0000000-0000-4000-8000-000000000001';
  default_org_id  uuid := '00000000-0000-4000-8000-000000000001';
  admin_email     text := 'admin@innover.com';
  encrypted_pw    text;
BEGIN
  encrypted_pw := crypt('Admin123!', gen_salt('bf', 10));

  -- Crear en auth.users si no existe
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = admin_email) THEN
    INSERT INTO auth.users (
      instance_id,
      id,
      aud,
      role,
      email,
      encrypted_password,
      email_confirmed_at,
      raw_app_meta_data,
      raw_user_meta_data,
      created_at,
      updated_at,
      confirmation_token,
      email_change,
      email_change_token_new,
      recovery_token
    ) VALUES (
      '00000000-0000-4000-8000-000000000000',
      default_user_id,
      'authenticated',
      'authenticated',
      admin_email,
      encrypted_pw,
      now(),
      '{"provider":"email","providers":["email"]}'::jsonb,
      '{"name":"Administrador","role":"admin"}'::jsonb,
      now(),
      now(),
      '',
      '',
      '',
      ''
    );

    -- Registrar identidad para inicio de sesión por email en Supabase Auth
    BEGIN
      INSERT INTO auth.identities (
        id,
        user_id,
        identity_data,
        provider,
        provider_id,
        last_sign_in_at,
        created_at,
        updated_at
      ) VALUES (
        default_user_id,
        default_user_id,
        format('{"sub":"%s","email":"%s"}', default_user_id, admin_email)::jsonb,
        'email',
        admin_email,
        now(),
        now(),
        now()
      )
      ON CONFLICT DO NOTHING;
    EXCEPTION
      WHEN undefined_column THEN
        INSERT INTO auth.identities (
          id,
          user_id,
          identity_data,
          provider,
          last_sign_in_at,
          created_at,
          updated_at
        ) VALUES (
          default_user_id,
          default_user_id,
          format('{"sub":"%s","email":"%s"}', default_user_id, admin_email)::jsonb,
          'email',
          now(),
          now(),
          now()
        )
        ON CONFLICT DO NOTHING;
    END;
  ELSE
    SELECT id INTO default_user_id FROM auth.users WHERE email = admin_email LIMIT 1;
  END IF;

  -- Crear o actualizar en public.agents
  INSERT INTO public.agents (
    id,
    user_id,
    organization_id,
    name,
    email,
    password,
    role,
    department,
    status,
    initials
  ) VALUES (
    1,
    default_user_id,
    default_org_id,
    'Administrador',
    admin_email,
    'Admin123!',
    'admin',
    'general',
    'offline',
    'AD'
  )
  ON CONFLICT (id) DO UPDATE
    SET user_id = default_user_id,
        organization_id = default_org_id,
        email = admin_email;

  -- Vincular a organization_members
  INSERT INTO public.organization_members (organization_id, agent_id, role, status)
  VALUES (default_org_id, 1, 'admin', 'active')
  ON CONFLICT (organization_id, agent_id) DO NOTHING;

END $$;
