-- =============================================================================
-- Multi-organization foundation
-- Preserves existing data by assigning it to a default organization.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.organizations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  legal_name text,
  tax_id text,
  email text,
  phone text,
  address text,
  logo_url text,
  timezone text NOT NULL DEFAULT 'America/Caracas',
  currency text NOT NULL DEFAULT 'USD',
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'suspended', 'inactive')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.organizations (id, name, slug)
VALUES (
  '00000000-0000-4000-8000-000000000001',
  'Innover',
  'innover'
)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.organization_members (
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  agent_id integer NOT NULL REFERENCES public.agents(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'advisor'
    CHECK (role IN ('owner', 'admin', 'supervisor', 'advisor')),
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'invited', 'inactive')),
  joined_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (organization_id, agent_id)
);

-- Keep organization_id directly on high-volume/domain tables. This makes
-- authorization predicates, Realtime filters and indexes deterministic.
DO $$
DECLARE
  table_name text;
  tenant_tables text[] := ARRAY[
    'agents',
    'clients',
    'conversations',
    'messages',
    'tickets',
    'labels',
    'quick_replies',
    'conversation_history',
    'history_messages',
    'crm_settings',
    'crm_payments',
    'crm_settings_history',
    'ai_tool_invocations',
    'ai_runs'
  ];
BEGIN
  FOREACH table_name IN ARRAY tenant_tables LOOP
    IF to_regclass('public.' || table_name) IS NOT NULL THEN
      EXECUTE format(
        'ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES public.organizations(id)',
        table_name
      );
      EXECUTE format(
        'UPDATE public.%I SET organization_id = $1 WHERE organization_id IS NULL',
        table_name
      ) USING '00000000-0000-4000-8000-000000000001'::uuid;
      EXECUTE format(
        'ALTER TABLE public.%I ALTER COLUMN organization_id SET DEFAULT %L::uuid',
        table_name,
        '00000000-0000-4000-8000-000000000001'
      );
      EXECUTE format(
        'ALTER TABLE public.%I ALTER COLUMN organization_id SET NOT NULL',
        table_name
      );
      EXECUTE format(
        'CREATE INDEX IF NOT EXISTS %I ON public.%I (organization_id)',
        table_name || '_organization_id_idx',
        table_name
      );
    END IF;
  END LOOP;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS crm_settings_organization_id_key
  ON public.crm_settings (organization_id);

INSERT INTO public.organization_members (organization_id, agent_id, role)
SELECT
  '00000000-0000-4000-8000-000000000001'::uuid,
  id,
  CASE
    WHEN lower(coalesce(role, '')) IN ('admin', 'administrador') THEN 'admin'
    ELSE 'advisor'
  END
FROM public.agents
ON CONFLICT (organization_id, agent_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.organization_integrations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  provider text NOT NULL CHECK (provider IN ('wispro', 'whatsapp')),
  status text NOT NULL DEFAULT 'disconnected'
    CHECK (status IN ('disconnected', 'pending', 'connected', 'error')),
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  credentials_encrypted text,
  last_verified_at timestamptz,
  last_error text,
  configured_by integer REFERENCES public.agents(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization_id, provider)
);

CREATE INDEX IF NOT EXISTS organization_integrations_provider_idx
  ON public.organization_integrations (provider, organization_id);

CREATE TABLE IF NOT EXISTS public.conversation_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  conversation_id bigint NOT NULL,
  agent_id integer REFERENCES public.agents(id) ON DELETE SET NULL,
  assigned_by integer REFERENCES public.agents(id) ON DELETE SET NULL,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  unassigned_at timestamptz,
  reason text
);

CREATE INDEX IF NOT EXISTS conversation_assignments_metrics_idx
  ON public.conversation_assignments (organization_id, agent_id, assigned_at DESC);

CREATE TABLE IF NOT EXISTS public.conversation_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  conversation_id bigint NOT NULL,
  agent_id integer REFERENCES public.agents(id) ON DELETE SET NULL,
  event_type text NOT NULL CHECK (
    event_type IN (
      'created',
      'assigned',
      'first_response',
      'resolved',
      'reopened',
      'transferred'
    )
  ),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS conversation_events_metrics_idx
  ON public.conversation_events (
    organization_id,
    event_type,
    occurred_at DESC
  );

-- New organization-management tables are server-only. Existing domain tables
-- remain compatible with the current client while data access is moved to
-- authenticated server routes.
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_integrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_events ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  table_name text;
  protected_tables text[] := ARRAY[
    'organizations',
    'organization_members',
    'organization_integrations',
    'conversation_assignments',
    'conversation_events'
  ];
BEGIN
  FOREACH table_name IN ARRAY protected_tables LOOP
    EXECUTE format(
      'DROP POLICY IF EXISTS service_role_all ON public.%I',
      table_name
    );
    EXECUTE format(
      'CREATE POLICY service_role_all ON public.%I FOR ALL TO service_role USING (true) WITH CHECK (true)',
      table_name
    );
  END LOOP;
END $$;

-- Domain data is available only through authenticated Next.js routes using
-- service_role. The browser anon key cannot bypass tenant checks.
DO $$
DECLARE
  table_name text;
  domain_tables text[] := ARRAY[
    'agents',
    'clients',
    'conversations',
    'messages',
    'tickets',
    'labels',
    'quick_replies',
    'conversation_history',
    'history_messages',
    'crm_settings',
    'crm_payments',
    'ai_runs',
    'ai_tool_invocations'
  ];
BEGIN
  FOREACH table_name IN ARRAY domain_tables LOOP
    IF to_regclass('public.' || table_name) IS NOT NULL THEN
      EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', table_name);
      EXECUTE format('DROP POLICY IF EXISTS service_role_all ON public.%I', table_name);
      EXECUTE format(
        'CREATE POLICY service_role_all ON public.%I FOR ALL TO service_role USING (true) WITH CHECK (true)',
        table_name
      );
    END IF;
  END LOOP;
END $$;

COMMENT ON COLUMN public.organization_integrations.credentials_encrypted IS
  'AES-256-GCM payload encrypted by the application; never return to clients.';

CREATE OR REPLACE FUNCTION public.capture_conversation_metrics()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.conversation_events (
      organization_id, conversation_id, agent_id, event_type, occurred_at
    ) VALUES (
      NEW.organization_id, NEW.id, NEW.agent_id, 'created',
      coalesce(NEW.created_at, now())
    );
    RETURN NEW;
  END IF;

  IF NEW.agent_id IS DISTINCT FROM OLD.agent_id AND NEW.agent_id IS NOT NULL THEN
    UPDATE public.conversation_assignments
    SET unassigned_at = now()
    WHERE organization_id = NEW.organization_id
      AND conversation_id = NEW.id
      AND unassigned_at IS NULL;

    INSERT INTO public.conversation_assignments (
      organization_id, conversation_id, agent_id, assigned_at
    ) VALUES (NEW.organization_id, NEW.id, NEW.agent_id, now());

    INSERT INTO public.conversation_events (
      organization_id, conversation_id, agent_id, event_type
    ) VALUES (
      NEW.organization_id,
      NEW.id,
      NEW.agent_id,
      CASE WHEN OLD.agent_id IS NULL THEN 'assigned' ELSE 'transferred' END
    );
  END IF;

  IF NEW.status = 'resuelto' AND OLD.status IS DISTINCT FROM 'resuelto' THEN
    INSERT INTO public.conversation_events (
      organization_id, conversation_id, agent_id, event_type
    ) VALUES (NEW.organization_id, NEW.id, NEW.agent_id, 'resolved');
  ELSIF OLD.status = 'resuelto' AND NEW.status IS DISTINCT FROM 'resuelto' THEN
    INSERT INTO public.conversation_events (
      organization_id, conversation_id, agent_id, event_type
    ) VALUES (NEW.organization_id, NEW.id, NEW.agent_id, 'reopened');
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS conversations_metrics_trigger ON public.conversations;
CREATE TRIGGER conversations_metrics_trigger
AFTER INSERT OR UPDATE OF agent_id, status ON public.conversations
FOR EACH ROW EXECUTE FUNCTION public.capture_conversation_metrics();

CREATE OR REPLACE FUNCTION public.capture_first_agent_response()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  conversation_created_at timestamptz;
  conversation_agent_id integer;
BEGIN
  IF NEW.type <> 'out' OR NEW.sender_type <> 'agent' THEN
    RETURN NEW;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.conversation_events
    WHERE organization_id = NEW.organization_id
      AND conversation_id = NEW.conversation_id
      AND event_type = 'first_response'
  ) THEN
    RETURN NEW;
  END IF;

  SELECT created_at, agent_id
  INTO conversation_created_at, conversation_agent_id
  FROM public.conversations
  WHERE id = NEW.conversation_id
    AND organization_id = NEW.organization_id;

  INSERT INTO public.conversation_events (
    organization_id,
    conversation_id,
    agent_id,
    event_type,
    metadata,
    occurred_at
  ) VALUES (
    NEW.organization_id,
    NEW.conversation_id,
    conversation_agent_id,
    'first_response',
    jsonb_build_object(
      'duration_ms',
      greatest(
        0,
        floor(
          extract(epoch FROM (coalesce(NEW.created_at, now()) - conversation_created_at))
          * 1000
        )
      )
    ),
    coalesce(NEW.created_at, now())
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS messages_first_response_trigger ON public.messages;
CREATE TRIGGER messages_first_response_trigger
AFTER INSERT ON public.messages
FOR EACH ROW EXECUTE FUNCTION public.capture_first_agent_response();
